server:
  port: 8080

spring:
  datasource:
    username: root
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  application:
    name: PRODUCT-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true